### ISSUE TITLE
Keine Unterobjekte mehr anlegbar

### ISSUE THREAD

**Issue by britter-decoit** [decoit/asterisk4ucs#17]
In der Testversion 1.0.10 können keine Unterobjekte mehr für den Asterisk-Server angelegt werden. Das System ist auf dem Stand 4.1-4 errata386.

![asterisk4ucs_bug_no_subobjects](https://cloud.githubusercontent.com/assets/1419612/22546052/9b441fee-e93b-11e6-8b8b-475e3ad3f6b6.jpg)

**Comment by spaceone** [comment]
Ich kann dir die UCS-Test-Pakete zukommen lassen.

**Comment by britter-decoit** [comment]
Gerne, wo kann ich die ziehen?

**Comment by spaceone** [comment]
ich habe sie dir gerade per E-Mail gesendet :)

**Comment by britter-decoit** [comment]
Mit den Paketen taucht links das Menü wieder auf. Wenn ich dort den Asterisk-Server markiere, kann ich die entsprechenden Unterobjekte anlegen. Markiere ich rechts in der Liste den Asterisk-Server kann ich weiterhin nur einen Asterisk-Server und ein Telefonbuch anlegen. Danke!

Ansonsten funktioniert die Erstellung, das Anlegen und Bearbeiten von Objekten. Wann kann man damit rechnen, dass die Pakete freigegeben werden?

**Comment by spaceone** [comment]
Ich denke, dass wir es nicht zu nächste Woche Mittwoch schaffen, da wir das UCS 4.2 MS1 Release machen. Daher vermute ich, dass es die darauffolgende Woche wird. Liegt leider nicht in meiner Hand.

**Comment by britter-decoit** [comment]
Das ist ja schon bald, das reicht völlig aus! Danke dir, vielmals!

**Comment by spaceone** [comment]
Super :)
