### ISSUE TITLE
UCS 4.x branch

### ISSUE THREAD

**Issue by spaceone** [decoit/asterisk4ucs#2]
Hello, there is only a branch for UCS 3.2. Could you create a branch with the latest version for UCS 4.1?

**Comment by commel** [comment]
We will do that, although the 3.2 branch works on 4.1 as well. There is a problem at the moment with editing or creating new objects in the ldap. Once it is fixed we will create a new branch for that.

**Comment by spaceone** [comment]
Yes, I am currently investigating to fix that problem.
I started with the following pull request: https://github.com/decoit/asterisk4ucs/pull/4

**Comment by britter-decoit** [comment]
Great! Okay let's move to a 4.1-branch then.

**Comment by spaceone** [comment]
You should revert the merge of Pull Request #4 in the UCS 3.2 branch. The code doesn't work with UCS 3.2.

**Comment by britter-decoit** [comment]
you're right. done
